### ISSUE TITLE
location of config file

### ISSUE THREAD

**Issue by nlights** [splitbrain/dokuwiki-plugin-redirect#2]
is it possible to save the config file redirect.conf in the conf directory instead of the plugin directory? if this would be the case, the plugin cuold be used in a dokuwiki farm setup.

**Comment by GJRobert** [comment]
As of Oct 2017, the config file is still located in `/lib/plugin/redirect`. May I ask what is the current status of this issue?

**Comment by GJRobert** [comment]
Thanks a million to Andi for taking time to address #2 and #20 ! The config file is now moved to `/conf`, and therefore I can split animal-specific pairs to `/<someAnimal>/conf/redirect.conf`. Working like a charm!
