### ISSUE TITLE
empty content

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [splitbrain/dokuwiki-plugin-redirect#29]
Hi,

after updating to version 2017-11-05 the content of the wiki pages remaines completely empty. Only the ".container-fluid" is filled. My template is bootstrap3.

Regards
Juergen

**Comment by splitbrain** [comment]
What DokuWiki version and what PHP version are you on? What do your error logs say?

**Comment by Juergen-aus-Koeln** [comment]
Release 2017-02-19b
PHP version 5.4.16
I don't know how to get the error log, could you please help me for this? Is there a special command for this?

**Comment by splitbrain** [comment]
Please refer to https://www.dokuwiki.org/bugs#how_to_obtain_additional_info

**Comment by mat-witts** [comment]
5.4 does not support const syntax in helper.php at lines 19 and 20. Update to php 5.6+ solves problem
