### ISSUE TITLE
Media redirects

### ISSUE THREAD

**Issue by Dr-Yukon** [splitbrain/dokuwiki-plugin-redirect#30]
Please add second admin config window for media's. I want to hold some media in the root and show it with shortened paths. Ex:
* page `deutsche/very/very/very/long/folders/path/index`
* has a syntax `{{./header.jpg}}`
* (**not a `{{/very/very/very/long/folders/path/header.jpg}}`!**)
* for `_media/very/very/very/long/folders/path/header.jpg`,
* redirected by media-rule `*:very:long:* very:long:$2`
* in `?do=admin&page=redirectmedia`

**Comment by Rainbow-Spike** [comment]
Used this in root .htaccess:
`RewriteRule ^_media/(..)[/:](.*)         lib/exe/fetch.php?media=$2  [QSA,L]
RewriteRule ^_detail/(..)[:/](.*)        lib/exe/detail.php?media=$2  [QSA,L]`
for 2-letter language ISO-codes
