### ISSUE TITLE
Wrong description on plugin page?

### ISSUE THREAD

**Issue by Chris75forumname** [splitbrain/dokuwiki-plugin-redirect#36]
Hi,
on the Plugin Page https://www.dokuwiki.org/plugin:redirect it says the following:
"The plugin stores a list of page/redirect pairs in a config file called redirect.conf in the plugin directory."
For me this did not work. Instead the file need be located in the dokuwiki/conf directory.
Just to be precise...
Yours!

**Comment by dregad** [comment]
I updated the wiki page. This issue can be closed.
